### PR TITLE
add young serif font

### LINKED ISSUE #124: [Font Request] Young Serif
Hi, thanks for this project! Would it be possible to add Young Serif?
https://github.com/uplaod/YoungSerif

### PR DESCRIPTION
**Pull request by vujevits**
fixes #124

### CODE REVIEW

**Comment by vujevits** [comment]
@KyleAMathews can you please review?

**Comment by KyleAMathews** [comment]
You shouldn't directly add packages — I run scripts locally to add the font files, etc. Is this font on fontsquirrel?

**Comment by vujevits** [comment]
Yes, I used the script for creating the PR:
https://www.fontsquirrel.com/fonts/youngserif
Sorry for the noise, the process for getting fonts published was not clear.

**Comment by KyleAMathews** [comment]
Yeah, it's not overly clear.

typeface-youngser is now published!

**Comment by vujevits** [comment]
Thanks!

**Pull request closed without merging**
