### PR TITLE
Add repository fields to packages.

### PR DESCRIPTION
**Pull request by knpwrs**
I came across the `work-sans` package on npm and was curious about where I could look at the source to get a quick peek at how the package was implemented. Without a repository field it was a bit of a wild goose chase.

Before you question my sanity, I did this with a script:

```sh
for package in *; do
  pck="$package/package.json"
  tmp="$pck.tmp"
  repo="https://github.com/KyleAMatthews/typefaces/tree/master/packages/$package"
  if [ -f "$pck" ]; then
    <$pck jq --arg repo $repo '. + {repository: $repo}' > $tmp
    mv -f $tmp $pck
  fi
done
```

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey Ken! We meet again :-D

Would you mind adding the change to the template for package files as well? https://github.com/KyleAMathews/typefaces/blob/master/scripts/templates.js

**Comment by knpwrs** [comment]
So we do! I'll go ahead and add a repository field to the template.

**Comment by knpwrs** [comment]
_ping_

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
